on:
  push:
     branches:
       - main

jobs:

  deploy-on-prod:
    runs-on: ssprod
    
    steps:
   
      # required for accessing files in repository.
      - name: Clone slotstat-next 
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:        
         owner: 'Slotstat'
         repository: 'slotstat-next'
         access-token: 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
    
      # https://github.com/marketplace/actions/build-number-generator
      - name: Npm Init
        run: npm i
      - name: Build On Machine
        run: npm run build
        
      - name: Run
        run: npm run start
      
