on:
  push:
     branches:
       - main

jobs:
  deploy-on-prod:
    runs-on: ssprod
    steps:
   
      # required for accessing files in repository.

      # https://github.com/marketplace/actions/build-number-generator
      - name: Npm Init
        run: npm i
      - name: Build On Machine
        run: npm run build
        
      - name: Run
        run: echo npm run start
      
